/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_keyword = 1,
  anon_sym_componentIdentifier = 2,
  sym_parameter = 3,
  sym_overrideBlock = 4,
  sym_type = 5,
  sym_statementEndBuffer = 6,
  anon_sym_SEMI = 7,
  aux_sym_statementEnd_token1 = 8,
  sym_componentName = 9,
  sym_identifier = 10,
  sym_dot = 11,
  sym_source_file = 12,
  sym_componentIdentifier = 13,
  sym_statement = 14,
  sym_identifierStatement = 15,
  sym_statementEnd = 16,
  sym_reftype = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_reftype_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_keyword] = "keyword",
  [anon_sym_componentIdentifier] = "componentIdentifier",
  [sym_parameter] = "parameter",
  [sym_overrideBlock] = "overrideBlock",
  [sym_type] = "type",
  [sym_statementEndBuffer] = "statementEndBuffer",
  [anon_sym_SEMI] = ";",
  [aux_sym_statementEnd_token1] = "statementEnd_token1",
  [sym_componentName] = "componentName",
  [sym_identifier] = "identifier",
  [sym_dot] = "dot",
  [sym_source_file] = "source_file",
  [sym_componentIdentifier] = "componentIdentifier",
  [sym_statement] = "statement",
  [sym_identifierStatement] = "identifierStatement",
  [sym_statementEnd] = "statementEnd",
  [sym_reftype] = "reftype",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_reftype_repeat1] = "reftype_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_keyword] = sym_keyword,
  [anon_sym_componentIdentifier] = anon_sym_componentIdentifier,
  [sym_parameter] = sym_parameter,
  [sym_overrideBlock] = sym_overrideBlock,
  [sym_type] = sym_type,
  [sym_statementEndBuffer] = sym_statementEndBuffer,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_statementEnd_token1] = aux_sym_statementEnd_token1,
  [sym_componentName] = sym_componentName,
  [sym_identifier] = sym_identifier,
  [sym_dot] = sym_dot,
  [sym_source_file] = sym_source_file,
  [sym_componentIdentifier] = sym_componentIdentifier,
  [sym_statement] = sym_statement,
  [sym_identifierStatement] = sym_identifierStatement,
  [sym_statementEnd] = sym_statementEnd,
  [sym_reftype] = sym_reftype,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_reftype_repeat1] = aux_sym_reftype_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_componentIdentifier] = {
    .visible = true,
    .named = false,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_overrideBlock] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_statementEndBuffer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_statementEnd_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_componentName] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_dot] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_componentIdentifier] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_identifierStatement] = {
    .visible = true,
    .named = true,
  },
  [sym_statementEnd] = {
    .visible = true,
    .named = true,
  },
  [sym_reftype] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_reftype_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(61);
      ADVANCE_MAP(
        '.', 72,
        ';', 68,
        'c', 35,
        'i', 9,
        'k', 15,
        'o', 56,
        'p', 5,
        't', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(60);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 69,
        '.', 72,
        ';', 68,
        'c', 34,
        'o', 56,
        'p', 5,
        '\t', 67,
        ' ', 67,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(2);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(72);
      if (lookahead == 'c') ADVANCE(34);
      if (lookahead == 'o') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == 'B') ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == 'I') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(62);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 30:
      if (lookahead == 'k') ADVANCE(65);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(70);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(70);
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 43:
      if (lookahead == 'p') ADVANCE(41);
      END_STATE();
    case 44:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(71);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(4);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 56:
      if (lookahead == 'v') ADVANCE(16);
      END_STATE();
    case 57:
      if (lookahead == 'w') ADVANCE(42);
      END_STATE();
    case 58:
      if (lookahead == 'y') ADVANCE(44);
      END_STATE();
    case 59:
      if (lookahead == 'y') ADVANCE(57);
      END_STATE();
    case 60:
      if (eof) ADVANCE(61);
      if (lookahead == '.') ADVANCE(72);
      if (lookahead == 'c') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(9);
      if (lookahead == 'k') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == 't') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_keyword);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_componentIdentifier);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_parameter);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_overrideBlock);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_type);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_statementEndBuffer);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_statementEnd_token1);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_componentName);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_dot);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [anon_sym_componentIdentifier] = ACTIONS(1),
    [sym_parameter] = ACTIONS(1),
    [sym_overrideBlock] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_componentName] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_dot] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym_statement] = STATE(4),
    [sym_identifierStatement] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_keyword] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(11), 2,
      anon_sym_SEMI,
      aux_sym_statementEnd_token1,
    ACTIONS(13), 2,
      sym_componentName,
      sym_dot,
    ACTIONS(9), 3,
      sym_parameter,
      sym_overrideBlock,
      sym_statementEndBuffer,
  [14] = 3,
    ACTIONS(13), 2,
      sym_componentName,
      sym_dot,
    ACTIONS(17), 2,
      anon_sym_SEMI,
      aux_sym_statementEnd_token1,
    ACTIONS(15), 3,
      sym_parameter,
      sym_overrideBlock,
      sym_statementEndBuffer,
  [28] = 4,
    ACTIONS(5), 1,
      sym_keyword,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(6), 3,
      sym_statement,
      sym_identifierStatement,
      aux_sym_source_file_repeat1,
  [43] = 6,
    ACTIONS(21), 1,
      anon_sym_componentIdentifier,
    ACTIONS(23), 1,
      sym_componentName,
    ACTIONS(25), 1,
      sym_dot,
    STATE(7), 1,
      sym_componentIdentifier,
    STATE(9), 1,
      sym_reftype,
    STATE(16), 1,
      aux_sym_reftype_repeat1,
  [62] = 4,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_keyword,
    ACTIONS(32), 1,
      sym_identifier,
    STATE(6), 3,
      sym_statement,
      sym_identifierStatement,
      aux_sym_source_file_repeat1,
  [77] = 5,
    ACTIONS(35), 1,
      sym_parameter,
    ACTIONS(37), 1,
      sym_overrideBlock,
    ACTIONS(39), 1,
      sym_statementEndBuffer,
    STATE(18), 1,
      sym_statementEnd,
    ACTIONS(41), 2,
      anon_sym_SEMI,
      aux_sym_statementEnd_token1,
  [94] = 4,
    ACTIONS(39), 1,
      sym_statementEndBuffer,
    ACTIONS(43), 1,
      sym_overrideBlock,
    STATE(15), 1,
      sym_statementEnd,
    ACTIONS(41), 2,
      anon_sym_SEMI,
      aux_sym_statementEnd_token1,
  [108] = 2,
    ACTIONS(47), 2,
      anon_sym_SEMI,
      aux_sym_statementEnd_token1,
    ACTIONS(45), 3,
      sym_parameter,
      sym_overrideBlock,
      sym_statementEndBuffer,
  [118] = 4,
    ACTIONS(39), 1,
      sym_statementEndBuffer,
    ACTIONS(49), 1,
      sym_overrideBlock,
    STATE(21), 1,
      sym_statementEnd,
    ACTIONS(41), 2,
      anon_sym_SEMI,
      aux_sym_statementEnd_token1,
  [132] = 3,
    ACTIONS(39), 1,
      sym_statementEndBuffer,
    STATE(19), 1,
      sym_statementEnd,
    ACTIONS(41), 2,
      anon_sym_SEMI,
      aux_sym_statementEnd_token1,
  [143] = 3,
    ACTIONS(39), 1,
      sym_statementEndBuffer,
    STATE(21), 1,
      sym_statementEnd,
    ACTIONS(41), 2,
      anon_sym_SEMI,
      aux_sym_statementEnd_token1,
  [154] = 3,
    ACTIONS(39), 1,
      sym_statementEndBuffer,
    STATE(22), 1,
      sym_statementEnd,
    ACTIONS(41), 2,
      anon_sym_SEMI,
      aux_sym_statementEnd_token1,
  [165] = 1,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_identifier,
  [171] = 1,
    ACTIONS(53), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_identifier,
  [177] = 3,
    ACTIONS(55), 1,
      sym_componentName,
    ACTIONS(57), 1,
      sym_dot,
    STATE(20), 1,
      aux_sym_reftype_repeat1,
  [187] = 1,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_identifier,
  [193] = 1,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_identifier,
  [199] = 1,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_identifier,
  [205] = 2,
    STATE(20), 1,
      aux_sym_reftype_repeat1,
    ACTIONS(65), 2,
      sym_componentName,
      sym_dot,
  [213] = 1,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_identifier,
  [219] = 1,
    ACTIONS(70), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_identifier,
  [225] = 1,
    ACTIONS(72), 2,
      anon_sym_SEMI,
      aux_sym_statementEnd_token1,
  [230] = 1,
    ACTIONS(74), 1,
      sym_type,
  [234] = 1,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 28,
  [SMALL_STATE(5)] = 43,
  [SMALL_STATE(6)] = 62,
  [SMALL_STATE(7)] = 77,
  [SMALL_STATE(8)] = 94,
  [SMALL_STATE(9)] = 108,
  [SMALL_STATE(10)] = 118,
  [SMALL_STATE(11)] = 132,
  [SMALL_STATE(12)] = 143,
  [SMALL_STATE(13)] = 154,
  [SMALL_STATE(14)] = 165,
  [SMALL_STATE(15)] = 171,
  [SMALL_STATE(16)] = 177,
  [SMALL_STATE(17)] = 187,
  [SMALL_STATE(18)] = 193,
  [SMALL_STATE(19)] = 199,
  [SMALL_STATE(20)] = 205,
  [SMALL_STATE(21)] = 213,
  [SMALL_STATE(22)] = 219,
  [SMALL_STATE(23)] = 225,
  [SMALL_STATE(24)] = 230,
  [SMALL_STATE(25)] = 234,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reftype, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reftype, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_reftype_repeat1, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reftype, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reftype, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_componentIdentifier, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentIdentifier, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statementEnd, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifierStatement, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statementEnd, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifierStatement, 3, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_reftype_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 5, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 6, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [76] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dmf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dmf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
