package main

type (
	ModelNodeKind string
)

const (
	SOURCE_FILE                 = "source_file"
	DMF_DECLARATION             = "dmf_declaration"
	MODEL_DECLARATION           = "model_declaration"
	IMPORT_BLOCK                = "import_block"
	IMPORT_STATEMENT            = "import_statement"
	MODEL_IDENTIFIER            = "model_identifier"
	MODEL_CONTENT               = "model_content"
	COMMENT_BLOCK               = "comment_block"
	PACKAGE_BLOCK               = "package_block"
	PACKAGE_CONTENT             = "package_content"
	STRUCT_BLOCK                = "struct_block"
	EXTENDS_BLOCK               = "extends_block"
	IMPLEMENTS_BLOCK            = "implements_block"
	STRUCT_CONTENT              = "struct_content"
	ARG_BLOCK                   = "arg_block"
	REF_BLOCK                   = "ref_block"
	FUNC_BLOCK                  = "func_block"
	PARAM_DEFINITION            = "param_definition"
	ENUM_BLOCK                  = "enum_block"
	ENUM_CONTENT                = "enum_content"
	ENUM_CONSTANT               = "enum_constant"
	ENUM_INDEX                  = "enum_index"
	ENTITY_BLOCK                = "entity_block"
	IDENTIFIER_STATEMENT        = "identifier_statement"
	INTERFACE_BLOCK             = "interface_block"
	INTERFACE_CONTENT           = "interface_content"
	NUMBER                      = "number"
	IDENTIFIER                  = "identifier"
	COMMENT                     = "comment"
	DOT                         = "dot"
	BYTE_CONTENT                = "byte_content"
	_SEMICOLON                  = "_semicolon"
	_COMMA                      = "_comma"
	_LEFT_BRACE                 = "_left_brace"
	_RIGHT_BRACE                = "_right_brace"
	_LEFT_BRACKET               = "_left_bracket"
	_RIGHT_BRACKET              = "_right_bracket"
	_LEFT_PAREN                 = "_left_paren"
	_RIGHT_PAREN                = "_right_paren"
	_AT                         = "_at"
	_NEW_LINE                   = "_new_line"
	REFTYPE                     = "reftype"
	PACKAGE_STRING              = "package_string"
	PRIMITIVE_TYPE              = "primitive_type"
	PRIMITIVE_VALUE             = "primitive_value"
	PACKAGE                     = "package"
	STRUCT                      = "struct"
	ENUM                        = "enum"
	ENTITY                      = "entity"
	INTERFACE                   = "interface"
	ARG                         = "arg"
	REF                         = "ref"
	FUNC                        = "func"
	EXPAND                      = "expand"
	EXTENDS                     = "extends"
	IMPLEMENTS                  = "implements"
	BYTE                        = "byte"
	INT                         = "int"
	LONG                        = "long"
	DOUBLE                      = "double"
	DATETIME                    = "datetime"
	DATE                        = "date"
	STRING                      = "string"
	BOOLEAN                     = "boolean"
	VOID                        = "void"
	VERSION_NUMBER              = "version_number"
	INTEGERVALUE                = "integerValue"
	LONGVALUE                   = "longValue"
	BOOLEANVALUE                = "booleanValue"
	BYTEVALUE                   = "byteValue"
	DOUBLEVALUE                 = "doubleValue"
	STRINGVALUE                 = "stringValue"
	STRING_CONTENT_SINGLE_QUOTE = "string_content_single_quote"
	STRING_CONTENT_DOUBLE_QUOTE = "string_content_double_quote"
	ESCAPE_SEQUENCE             = "escape_sequence"
	DATETIMEVALUE               = "dateTimeValue"
	TIMEVALUE                   = "timeValue"
	DATEVALUE                   = "dateValue"
)
